### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nicko-winner** [rackerlabs/helix-react#3]
# Tentative Roadmap

## Phase 0
- Document contribution guidelines (core maintainers, review process, etc.)
- Initialize Wiki to document standards (naming, structure, ~tabs vs~ spaces, etc.)
- Prototype dev pipeline (How will a contributor add/update features?)
    - Build with TypeScript to export HelixUI type definitions?
    - React storybook (or equivalent library) to easily publish component documentation

## Phase 1
- Finalize dev pipeline
- Publish component documentation
- Build component for every HelixUI element that emits custom events (see  "Custom Elements" docs at https://rackerlabs.github.io/helix-ui)
- CI/CD Pipeline (Travis/CircleCI, Enzyme, etc.)

## Phase 2
- Build components for CSS-based HelixUI components (e.g., radio, select, pagination, etc.)

**Comment by CITguy** [comment]
## Phase 1
- React storybook (or equivalent) to document the library components.

**Comment by CITguy** [comment]
Closing. Migrated to [wiki](https://github.com/rackerlabs/helix-react/wiki/Roadmap)
